//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invent.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventarizationEntities4 : DbContext
    {
        public InventarizationEntities4()
            : base("name=InventarizationEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<DefectiveList> DefectiveList { get; set; }
        public virtual DbSet<Expert> Expert { get; set; }
        public virtual DbSet<Expertise> Expertise { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InvSchedule> InvSchedule { get; set; }
        public virtual DbSet<MoveStatement> MoveStatement { get; set; }
        public virtual DbSet<ObjectType> ObjectType { get; set; }
        public virtual DbSet<ScheduleContext> ScheduleContext { get; set; }
        public virtual DbSet<StatementContext> StatementContext { get; set; }
        public virtual DbSet<Subdivision> Subdivision { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Waybill> Waybill { get; set; }
        public virtual DbSet<WaybillContext> WaybillContext { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WriteOffAct> WriteOffAct { get; set; }
        public virtual DbSet<WriteOffReason> WriteOffReason { get; set; }
    }
}
