//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invent.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaybillContext
    {
        public int MoveStatementIDStatement { get; set; }
        public int WaybillIDWaybill { get; set; }
        public int IDContext { get; set; }
    
        public virtual MoveStatement MoveStatement { get; set; }
        public virtual Waybill Waybill { get; set; }
    }
}
