//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invent.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOffAct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WriteOffAct()
        {
            this.DefectiveList = new HashSet<DefectiveList>();
        }
    
        public int IDWriteOffAct { get; set; }
        public System.DateTime WriteOffDate { get; set; }
        public Nullable<int> WriteOffReasonIDReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefectiveList> DefectiveList { get; set; }
        public virtual WriteOffReason WriteOffReason { get; set; }
    }
}
